# Generated by Django 5.0.7 on 2024-07-11 14:59

from django.db import migrations, models

import setting.models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
