# Generated by Django 5.0.7 on 2024-07-11 14:59

import setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='image',
            field=models.ImageField(null=True, upload_to=setting.models.specialty_image_directory_path),
        ),
    ]
