# Generated by Django 5.0.7 on 2024-07-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_specialty_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='image',
            field=models.ImageField(null=True, upload_to='specialties/'),
        ),
    ]
