# Generated by Django 5.0.6 on 2024-07-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_gender_alter_account_phone_number_visittime'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
