# Generated by Django 5.0.7 on 2024-07-15 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_doctor_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=500000),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1),
        ),
        migrations.AlterField(
            model_name='visittime',
            name='weekday',
            field=models.CharField(choices=[('SAT', 'شنبه'), ('SUN', 'یکشنبه'), ('MON', 'دوشنبه'), ('TUE', 'سه شنبه'), ('WED', 'چهارشنبه'), ('THU', 'پنج شنبه'), ('FRI', 'جمعه')], max_length=3),
        ),
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(default='336265', max_length=6)),
                ('tp_created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
