# Generated by Django 5.0.7 on 2024-07-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_account_balance_alter_account_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='265196', max_length=6),
        ),
    ]
