# Generated by Django 5.0.7 on 2024-07-19 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visittime',
            name='weekday',
        ),
        migrations.AddField(
            model_name='visittime',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='284048', max_length=6),
        ),
    ]
