# Generated by Django 5.0.7 on 2024-07-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_visittime_weekday_visittime_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='992192', max_length=6),
        ),
    ]
