# Generated by Django 5.0.7 on 2024-07-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_comment'),
        ('user', '0008_doctor_avg_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.doctor'),
            preserve_default=False,
        ),
    ]
